services:
  auction.api:
    image: auction.api
    build:
      context: .
      dockerfile: Auction.Api/Dockerfile
  
  auction.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: auction
      POSTGRES_PASSWORD: auction
      POSTGRES_DB: AuctionDb
    ports:
      - "5432:5432"
    volumes:
      - ./Volumes/auction-db:/var/lib/postgresql/data